name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.pull_request.PULL_REQUEST_NUMBER }}

env:
  node_version: 26

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: "pnpm"
      - name: install
        run: pnpm i --frozen-lockfile

      - name: Check types
        run: pnpm run tsc:check
